ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
#
RUN addgroup -g ${PGID} -S influxdb && \
        adduser -u ${PUID} -G influxdb -h /var/lib/influxdb -D influxdb
RUN set -ex && \
    echo 'hosts: files dns' >> /etc/nsswitch.conf && \
    apk add -Uu --no-cache --virtual .build-deps wget gnupg tar ca-certificates && \
    update-ca-certificates && \
    for key in \
        05CE15085FC09D18E99EFB22684A14CF2582E0C5 ; \
    do \
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" || \
        gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
        gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
    done && \
    cd /tmp/ && \
    wget -q https://dl.influxdata.com/influxdb/nightlies/influxdb-nightly_linux_armhf.tar.gz.asc && \
    wget -q https://dl.influxdata.com/influxdb/nightlies/influxdb-nightly_linux_armhf.tar.gz && \
    gpg --batch --verify influxdb-nightly_linux_amd64.tar.gz.asc influxdb-nightly_linux_armhf.tar.gz && \
    mkdir -p /usr/src && \
    tar -C /usr/src -xzf influxdb-nightly_linux_armhf.tar.gz && \
    rm -f /usr/src/influxdb-*/influxdb.conf && \
    chmod +x /usr/src/influxdb-*/* && \
    cp -a /usr/src/influxdb-*/* /usr/bin/ && \
    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
    apk del .build-deps && \
	rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME  ["/var/lib/influxdb"]
#
EXPOSE 8083 8086 8088 8091 4242
#
ENTRYPOINT ["/init"]
