ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1000
ARG PGID=1000
#
RUN addgroup -g ${PGID} -S influxdb \
    && adduser -u ${PUID} -G influxdb -h /var/lib/influxdb -D influxdb \
    && echo 'hosts: files dns' >> /etc/nsswitch.conf \
    && apk add -Uu --purge --no-cache \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
        ca-certificates \
        influxdb \
    && update-ca-certificates \
	&& rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME  ["/var/lib/influxdb"]
#
EXPOSE 8083 8086 8088 8091 4242
#
ENTRYPOINT ["/init"]
