#!/usr/bin/with-contenv bash
set -e

INFLUXDB_CONFIG_PATH="${INFLUXDB_CONFIG_PATH:-/etc/influxdb.conf}";
# INFLUXDB_ARGS="${INFLUXDB_ARGS:- }";

s6-setuidgid ${S6_USER:-alpine} \
exec \
    influxd run \
    -config "${INFLUXDB_CONFIG_PATH}" \
    ${INFLUXDB_ARGS}
